
- name: work with ec2
  hosts: localhost

  tasks:
    - name: get instances with tag Name Dynatrace_Managed  
      ec2_instance_info:
        region: eu-west-1
        filters:  
           "tag:Name": Dynatrace_Managed
#           instance-state-name: [ "running" ]
      register: ec2_instances

    - name: print output
      debug: 
        msg: "instances found: {{ lookup('ansible.utils.to_paths', ec2_instances) }}" 
     
    - name: initialize instances list
      set_fact: 
         ids: []  

    - name: list all ec2 instnces matched
      set_fact:
        ids: "{{ ids + [ item['instance_id'] ] }}"
      loop: "{{ ec2_instances['instances'] }}" 
 
